#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v12
# autospec commit: 381dfd8
#
Name     : R-ucminf
Version  : 1.2.2
Release  : 49
URL      : https://cran.r-project.org/src/contrib/ucminf_1.2.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/ucminf_1.2.2.tar.gz
Summary  : General-Purpose Unconstrained Non-Linear Optimization
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-ucminf-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
The algorithm is of quasi-Newton type with BFGS updating of the inverse
             Hessian and soft line search with a trust region type monitoring of the
             input to the line search algorithm. The interface of 'ucminf' is
             designed for easy interchange with 'optim'.

%package lib
Summary: lib components for the R-ucminf package.
Group: Libraries

%description lib
lib components for the R-ucminf package.


%prep
%setup -q -n ucminf
pushd ..
cp -a ucminf buildavx2
popd
pushd ..
cp -a ucminf buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719275992

%install
export SOURCE_DATE_EPOCH=1719275992
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/ucminf/DESCRIPTION
/usr/lib64/R/library/ucminf/INDEX
/usr/lib64/R/library/ucminf/Meta/Rd.rds
/usr/lib64/R/library/ucminf/Meta/features.rds
/usr/lib64/R/library/ucminf/Meta/hsearch.rds
/usr/lib64/R/library/ucminf/Meta/links.rds
/usr/lib64/R/library/ucminf/Meta/nsInfo.rds
/usr/lib64/R/library/ucminf/Meta/package.rds
/usr/lib64/R/library/ucminf/NAMESPACE
/usr/lib64/R/library/ucminf/NEWS.md
/usr/lib64/R/library/ucminf/R/ucminf
/usr/lib64/R/library/ucminf/R/ucminf.rdb
/usr/lib64/R/library/ucminf/R/ucminf.rdx
/usr/lib64/R/library/ucminf/help/AnIndex
/usr/lib64/R/library/ucminf/help/aliases.rds
/usr/lib64/R/library/ucminf/help/paths.rds
/usr/lib64/R/library/ucminf/help/ucminf.rdb
/usr/lib64/R/library/ucminf/help/ucminf.rdx
/usr/lib64/R/library/ucminf/html/00Index.html
/usr/lib64/R/library/ucminf/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/ucminf/libs/ucminf.so
/V4/usr/lib64/R/library/ucminf/libs/ucminf.so
/usr/lib64/R/library/ucminf/libs/ucminf.so
